# Generated by Django 5.0 on 2023-12-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
